version: "3.3"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}
  organizr:
    container_name: organizr
    restart: always
    image: lsiocommunity/organizr
    volumes:
      - ${USERDIR}/docker/organizr:/config
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "80:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  webthings-gateway:
    container_name: webthings-gateway
    image: mozillaiot/gateway:latest
    restart: unless-stopped
    network_mode: host
    # "ports" are ignored because of "network_mode: host". Either use "ports"
    # or "network_mode: host".
    #ports:
      #- "9006:8080"
      #- "9007:4443"
    environment:
      - "TZ=America/New_York"
    volumes:
      - /opt/docker/webthings-gateway:/home/node/.mozilla-iot
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    # If certain devices are needed, e.g. USB dongles, enable them here.
    #devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
    #  - /dev/ttyACM0:/dev/ttyACM0
    # If Bluetooth, the container needs to run in privileged mode.
    #privileged: true

  nzbget:
    image: "linuxserver/nzbget"
    container_name: "nzbget"
    volumes:
      - ${USERDIR}/docker/nzbget:/config
      - ${USERDIR}/downloads:/downloads
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "9001:6789"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  sonarr:
    image: "linuxserver/sonarr"
    container_name: "sonarr"
    volumes:
      - ${USERDIR}/docker/sonarr:/config
      - ${USERDIR}/downloads/completed:/downloads
      - ${USERDIR}/downloads/completed/Series:/tv
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    ports:
        - "9002:8989"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  radarr:
    image: "linuxserver/radarr"
    container_name: "radarr"
    volumes:
      - ${USERDIR}/docker/radarr:/config
      - ${USERDIR}/downloads/completed:/downloads
      - ${USERDIR}/downloads/completed/Movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "9003:7878"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  plexms:
    container_name: plexms
    restart: always
    image: plexinc/pms-docker
    volumes:
      - ${USERDIR}/docker/plexms:/config
      - /tmp:/transcode
      - ${USERDIR}/downloads/completed:/data
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=${TZ}
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM="claim-yBPds7QbLZk1U7XEuHMW"
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP="http://192.168.1.100:32400/"

  hydra:
    image: "linuxserver/hydra"
    container_name: "hydra"
    volumes:
      - ${USERDIR}/docker/hydra:/config
      - ${USERDIR}/downloads:/downloads
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "9004:5075"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} 

  nextcloud:
    container_name: nextcloud
    restart: always
    image: linuxserver/nextcloud
    volumes:
      - ${USERDIR}/docker/nextcloud:/config
      - ${USERDIR}/shared_data:/data
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "9005:443"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  bind:
    container_name: bind
    restart: always
    image: sameersbn/bind
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
    - /srv/docker/bind:/data
