version: "3.3"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
      - ${USERDIR}/docker/shared:/shared
    environment:
      - TZ=${TZ}

  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr
    restart: always
    ports:
        - 80:80
    volumes:
        - /home/organizr:/config
    volumes:
      - ${USERDIR}/docker/organizr:/config
      - ${USERDIR}/docker/shared:/shared
    environment:
        - fpm=true #true or false | using true will provide better performance
        - branch=v2-master #v2-master or #v2-develop
        - PUID=1000
        - PGID=1000
        - TZ=${TZ}

  nzbget:
    image: "linuxserver/nzbget"
    container_name: "nzbget"
    volumes:
      - /mnt/external1/config/nzbget:/config
      - /mnt/external1/downloads:/downloads
      - /mnt/external1/shared:/shared
    ports:
      - "9001:6789"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  sonarr:
    image: "linuxserver/sonarr"
    container_name: "sonarr"
    volumes:
      - /mnt/external1/config/sonarr:/config
      - /mnt/external1//downloads/completed:/downloads
      - /mnt/external1/downloads/completed/Series:/tv
      - "/etc/localtime:/etc/localtime:ro"
      - /mnt/external1/shared:/shared
    ports:
        - "9002:8989"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  radarr:
    image: "linuxserver/radarr"
    container_name: "radarr"
    volumes:
      - /mnt/external1/config/radarr:/config
      - /mnt/external1/downloads/completed:/downloads
      - /mnt/external1/downloads/completed/Movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
      - /mnt/external1/shared:/shared
    ports:
      - "9003:7878"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  plexms:
    container_name: plexms
    restart: always
    image: plexinc/pms-docker
    volumes:
      - /mnt/external1/config/plexms:/config
      - /tmp:/transcode
      - /mnt/external1/downloads/completed:/data
      - /mnt/external1/shared:/shared
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=${TZ}
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM="claim-yBPds7QbLZk1U7XEuHMW"
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP="http://192.168.1.100:32400/"

  hydra:
    image: "linuxserver/hydra"
    container_name: "hydra"
    volumes:
      - ${USERDIR}/docker/hydra:/config
      - ${USERDIR}/downloads:/downloads
      - ${USERDIR}/docker/shared:/shared
    ports:
      - "9004:5075"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} 

  bind:
    container_name: bind
    restart: always
    image: sameersbn/bind
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
    - /srv/docker/bind:/data

  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "${USERDIR}:/home/server/"
      - "${USERDIR}/pure-ftpd/passwd:/etc/pure-ftpd/passwd"
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: server
      FTP_USER_PASS: server
      FTP_USER_HOME: /home/server
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
    restart: always

  nextcloud:
    container_name: nextcloud
    restart: always
    image: linuxserver/nextcloud
    volumes:
      - /mnt/external1/config/nextcloud:/config
      - /mnt/external1/shared_data:/data
      - /mnt/external1/shared:/shared
    ports:
      - "9005:443"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  phpmyadmin:
    hostname: phpmyadmin
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mariadb:db
    ports:
      - 9006:80
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  # to check ip: docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mariadbtest
  # source: https://mariadb.com/kb/en/installing-and-using-mariadb-via-docker/
  mariadb:
    image: "linuxserver/mariadb"
    container_name: "mariadb"
    hostname: mariadb
    volumes:
        - /mnt/external1/config/mariadb:/config
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  qbittorrent:
    image: "linuxserver/qbittorrent"
    container_name: "qbittorrent"
    volumes:
      - /mnt/external1/config/qbittorrent:/config
      - /mnt/external1/downloads/completed:/downloads
      - /mnt/external1/shared:/shared
    ports:
      - "9007:9007"
      - "6881:6881"
      - "6881:6881/udp"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
      - WEBUI_PORT=9007

  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
